name: GitHub Actions Demo
on: [push]
env:
  TOKEN_KEY: 'accessTokenKey'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Modules
        run: yarn
      - name: Install Server Modules
        run: cd server && yarn
      - name: Install Client Modules
        run: cd ../client && yarn
      - name: Run Server Tests
        run: cd server && yarn test
      - name: Run Client Tests
        run: cd ../client && yarn test
